<?php

namespace App\Model;

class TPIResourcesModel
{
    const URL_ROLES = 'https://release.botc.app/resources/data/roles.json';
    const URL_JINXES = 'https://release.botc.app/resources/data/jinxes.json';
    const URL_NIGHTSHEET = 'https://release.botc.app/resources/data/nightsheet.json';

    /**
     * Gets the special roles from the JSON file.
     *
     * @return array Success status and the body of the results.
     */
    public function getLocal(string $filename): array
    {
        // $file = $this->dataDirectory . DIRECTORY_SEPARATOR . $filename;
        $file = $filename;

        if (!file_exists($file)) {
            return ['success' => false, 'body' => "'{$file}' not found"];
        }

        return $this->getContentsAsJson($file);
    }

    /**
     * Gets the JSON from the given URL.
     *
     * @param string $url URL to find the JSON.
     * @return array The success status body of the results.
     */
    public function getRemote(string $url): array
    {
        return $this->getContentsAsJson($url);
    }

    public function getImages(): array
    {
        $path = '/../../assets/img/roles';
        $realpath = realpath(dirname(__FILE__) . $path);
        $files = scandir($realpath);

        return array_filter($files, function ($item) {
            return pathinfo($item, PATHINFO_EXTENSION) === 'webp';
        });
    }

    public function combineRoles(
        array $roles,
        array $nightsheet,
        array $images,
    ): array {
        $combined = [];

        usort($combined, function ($a, $b) {
            return $a['id'] <=> $b['id'];
        });

        return $combined;
    }

    /**
     * Cleans the given text to remove any instance of ":reminder:" (and any
     * extra spaces generated by that removal).
     *
     * @param string $nightReminder Night reminder to clean.
     * @return string Cleaned night reminder.
     */
    public function cleanNightReminder(string $nightReminder)
    {
        $removed = str_replace(':reminder:', '', $nightReminder);
        $unspaced = preg_replace('/\s+/', ' ', $removed);
        
        // Fix the Po.
        $unorred = preg_replace('/\.\s+[a-z]\s+$/i', '', $unspaced);
        $despaced = preg_replace('/\s+/', ' ', $unorred);

        return (string) $despaced;
    }

    /**
     * Gets the contents of the given source and attempts to parse it as JSON,
     * returning an array with a "success" key and a "body" key.
     *
     * @param string $source Source of the contents to get and parse.
     * @return array Results of parsing the contents (if possible).
     */
    protected function getContentsAsJson(string $source): array
    {
        $contents = file_get_contents($source);

        if ($contents === false) {
            return ['success' => false, 'body' => "'{$source}' not found"];
        }

        if (!json_validate($contents)) {
            return ['success' => false, 'body' => "'{$source}' not valid JSON"];
        }

        $decoded = json_decode($contents, true);

        if (!is_array($decoded)) {
            return ['success' => false, 'body' => 'JSON not an array'];
        }

        return ['success' => true, 'body' => $decoded];
    }
}
