<?php

namespace App\Model;

class TPIResourcesModel
{
    /**
     * @var string Location wrapper for the images.
     */
    const LOCATION_IMAGES = '/build/img/roles/%s.webp';

    /**
     * Combines the data.
     *
     * @param array $roles Raw roles to modify.
     * @param array $nightsheet Night sheet for the first and other nightrs.
     * @return array Combined data.
     */
    public function combineRoles(
        array $roles,
        array $nightsheet,
    ): array {
        $combined = [];

        $firstNight = $nightsheet['firstNight'];
        $otherNight = $nightsheet['otherNight'];

        foreach ($roles as $role) {
            $role['firstNight'] = 0;
            $role['otherNight'] = 0;

            if (($firstIndex = array_search($role['id'], $firstNight)) !== false) {
                $role['firstNight'] = $firstIndex;
            }

            if (($otherIndex = array_search($role['id'], $otherNight)) !== false) {
                $role['otherNight'] = $otherIndex;
            }

            $role['image'] = $this->generateImages($role['id'], $role['team']);

            $combined[] = $role;
        }

        usort($combined, function ($a, $b) {
            return $a['id'] <=> $b['id'];
        });

        return $combined;
    }

    /**
     * Cleans the given text to remove any instance of ":reminder:" (and any
     * extra spaces generated by that removal).
     *
     * @param string $nightReminder Night reminder to clean.
     * @return string Cleaned night reminder.
     */
    public function cleanNightReminder(string $nightReminder)
    {
        $removed = str_replace(':reminder:', '', $nightReminder);
        $unspaced = preg_replace('/\s+/', ' ', $removed);
        
        // Fix the Po.
        $unorred = preg_replace('/\.\s+[a-z]\s+$/i', '', $unspaced);
        $despaced = preg_replace('/\s+/', ' ', $unorred);

        return (string) $despaced;
    }

    /**
     * Generates the images for the given role.
     *
     * @param string $id Role ID.
     * @param string $team Role's team.
     * @return array Array of image locations.
     */
    protected function generateImages(string $id, string $team): array
    {
        $images = [];

        switch ($team) {
        case 'fabled':
        case 'loric':
            $images = [
                $id,
            ];
            break;

        case 'townsfolk':
        case 'outsider':
            $images = [
                "{$id}_g",
                "{$id}_e",
            ];
            break;

        case 'minion':
        case 'demon':
            $images = [
                "{$id}_e",
                "{$id}_g",
            ];
            break;

        case 'traveller':
            $images = [
                $id,
                "{$id}_g",
                "{$id}_e",
            ];
            break;
        }

        return array_map(function ($image) {
            return sprintf(static::LOCATION_IMAGES, $image);
        }, $images);
    }
}
