---
tb:
- id: _meta
  firstNight:
  - dusk
  - minioninfo
  - demoninfo
  - poisoner
  - spy
  - washerwoman
  - librarian
  - investigator
  - chef
  - empath
  - fortuneteller
  - butler
  - dawn
  otherNight:
  - dusk
  - poisoner
  - monk
  - spy
  - scarletwoman
  - imp
  - ravenkeeper
  - undertaker
  - empath
  - fortuneteller
  - butler
  - dawn
- washerwoman
- librarian
- investigator
- chef
- empath
- fortuneteller
- undertaker
- monk
- ravenkeeper
- virgin
- slayer
- soldier
- mayor
- butler
- saint
- recluse
- drunk
- poisoner
- spy
- baron
- scarletwoman
- imp
- scapegoat
- gunslinger
- beggar
- bureaucrat
- thief
bmr:
- grandmother
- sailor
- chambermaid
- exorcist
- innkeeper
- gambler
- gossip
- courtier
- professor
- minstrel
- tealady
- pacifist
- fool
- goon
- lunatic
- tinker
- moonchild
- godfather
- devilsadvocate
- assassin
- mastermind
- zombuul
- pukka
- shabaloth
- po
- apprentice
- matron
- voudon
- judge
- bishop
snv:
- clockmaker
- dreamer
- snakecharmer
- mathematician
- flowergirl
- towncrier
- oracle
- savant
- seamstress
- philosopher
- artist
- juggler
- sage
- mutant
- sweetheart
- barber
- klutz
- eviltwin
- witch
- cerenovus
- pithag
- fanggu
- vigormortis
- nodashii
- vortox
- butcher
- bonecollector
- harlot
- barista
- deviant

